Dev Environment Setup
Roommate-Budget-Helper/budget-helper-webui pull request #1
Opened 2022-10-03 14:22 UTC by RealJasomo

## Jira Ticket: [RBH-16](https://roommatebudgethelper.atlassian.net/browse/RBH-16?atlOrigin=eyJpIjoiN2NiZDRlZWM1OTQzNGMzMDliOTI1OGIwMmI0ZmY2OTYiLCJwIjoiaiJ9)

## Description of Work
Generated the initial boilerplate for the project and got various configuration files setup
## Acceptance Criteria

- Initial boilerplate for NextJS, Tailwind, Prisma, NextAuth, and tRPC
- eslint and prettier configured
- Github actions pipeline created
- Docker-compose for local test services (Postgres database)
- Onboarded Deepsource SCA

## How to Test

- Follow setups in app/README.md and verify that the project can be run from your computer

### List of Changes:

- t3-stack boilerplate
- Readme created for setting up the project
- docker files created

2022-10-03 14:48 UTC, RealJasomo commented
Should be working, but fails due to needing the secrets set under Settings > Security/Secrets >Actions

2022-10-03 21:05 UTC, DavidPurdy1 requested changes
Looks pretty good. I would like the instructions to be a little more in depth because there was a couple things that came up. I would really like 1-2 more people to review this since it is the setup we will be using for this project and this is a lot of files (and I'm not too experienced what some of these boilerplate files do). @rhit-daviscl @cryerca

2022-10-03 21:05 UTC, DavidPurdy1 commented on app/prisma/schema.prisma
> +// This is your Prisma schema file,
This is cool, makes things a lot easier.

2022-10-03 21:17 UTC, RealJasomo commented on app/.gitignore
> +.vercel
That was part of autogenerated code

2022-10-03 21:17 UTC, RealJasomo commented on app/.prettierrc.json
> +    "semi": false,
That's a good point, changed it to reflect that.

2022-10-03 21:19 UTC, RealJasomo commented on app/next-env.d.ts
> +/// <reference types="next" />
This is a triple-slash directive. You can find out more about them [here](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html). Basically this file is for module type definitions and is part of the boilerplate

2022-10-03 21:20 UTC, RealJasomo commented on app/README.md
> +NEXTAUTH_SECRET=<enter a secure key here>
This secure key is just a random secret for authentication. It can be anything you want since it is local

2022-10-03 21:20 UTC, RealJasomo commented on app/README.md
> +   `git clone git@github.com:Roommate-Budget-Helper/budget-helper-backend.git` - Note if you do not have SSH key setup for GitHub, follow this guide before running the above command: [Adding SSH key
Good catch, I copied the wrong repo lol

2022-10-03 21:21 UTC, RealJasomo commented on .deepsource.toml
> +  [analyzers.meta]
Not sure, this was autogenerated by deep source so I left it as is.

2022-10-03 23:45 UTC, rhit-daviscl reviewed
Overall looks good to me. David covered the areas that could be shrunken down and most the others are added automatically, to a degree. All good from me, but lets have others try and set their dev up before we approve and merge.

2022-10-03 23:45 UTC, rhit-daviscl commented on app/README.md
> +COGNITO_CLIENT_SECRET=<replace with actual cognito secret>
These will be for when we are confirming our AWS connections, correct?
Asked in Teams, but asked again for GitHub.

2022-10-04 16:51 UTC, DavidPurdy1 commented on app/next-env.d.ts
> +/// <reference types="next" />
Okay thanks

2022-10-04 16:51 UTC, DavidPurdy1 commented on .deepsource.toml
> +  [analyzers.meta]
Okay, I don't care a ton either, just trying to get things to look nice.

2022-10-04 16:55 UTC, DavidPurdy1 commented on app/README.md
> +8. Open the repository you cloned with the file selection window
Okay I was able to get the dev environment setup on my windows machine working fine. Considering you've been able to on a Linux VM and my Linux Machine is currently broken, I would say it is probably an issue with my machine. The only other thing that would be nice is if we could get picture steps for the readme, but not super important.

2022-10-04 17:00 UTC, DavidPurdy1 approved these changes
Alright, I am happy with the dev environment setup. I am going to go ahead an approve and it's up to you if you want to check with everyone else regarding any issues. Nice work.

2022-10-04 17:37 UTC, merged